name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-test:
    strategy:
      matrix:
        python-version: [3.9.6]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Switch to Current Branch
      run: git checkout ${{ env.BRANCH }}
            
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install -e .

    - name: Run unit tests
      run: |
        pip install -r src/test-requirements.txt
        python -m pytest --import-mode=append src/tests/
  
  build-docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --tag publicbullet:$(date +%s) src/.